@startuml ModelClassDiagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueFoodplaceList
Class Foodplace
Class Address
Class Cuisine
Class Email
Class Name
Class Note
Class Phone
Class Pinned
Class Rate
Class Tag
Class Timing
Class Wishlist
Class Blacklist

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueFoodplaceList
UniqueFoodplaceList --> "~* all" Foodplace
Foodplace *--> Name
Foodplace *--> Phone
Foodplace *--> Email
Foodplace *--> Address
Foodplace *--> "*" Tag
Foodplace *--> Cuisine
Foodplace *--> Timing
Foodplace *--> Note
Foodplace *--> Pinned
Foodplace *--> Rate
Foodplace *--> Wishlist
Foodplace *--> Blacklist

Foodplace -[hidden]up--> I
UniqueFoodplaceList -[hidden]right-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Email -[hidden]right-> Timing
Timing -[hidden]right-> Cuisine
Cuisine -[hidden]right-> Note
Note -[hidden]right-> Tag
Tag -[hidden]right-> Rate
Rate -[hidden]right-> Wishlist
Wishlist -[hidden]right-> Pinned

ModelManager --> "~* filtered" Foodplace
@enduml
